import request from "./request.js";

export default {
  miniappLogin: (params) => request("/member.Login/miniapp", params, "post"),
  miniappByPhone: (params) => request("/member.Login/miniappByPhone", params, "post"),
  accountLogin: (params) => request("/member.Login/login", params, "post"),
  logout: (params) => request("/member.Logout/logout", params, "post"),
  getMemberInfo: (params) => request("/member.Member/memberInfo", params, "get"),
  editUserInfo: (params) => request("/member.Member/edit", params, "post"),
  phoneCaptcha: (params) => request("/member.Login/phoneCaptcha", params, "get"),
  phoneLogin: (params) => request("/member.Login/phoneLogin", params, "post"),
  shopCartAdd: (params) => request("/member.MemberShopCart/add", params, "post"),
  shopCartList: (params) => request("/member.MemberShopCart/list", params, "get"),
  shopCartDel: (params) => request("/member.MemberShopCart/dele", params, "post"),
  shopCartEdit: (params) => request("/member.MemberShopCart/edit", params, "post"),
  getConfirmOrder: (params) => request("/member.MemberOrder/getConfirmOrder", params, "post"),
  confirmOrder: (params) => request("/member.MemberOrder/confirmOrder", params, "post"),
  getOrderParams: (params) => request("/member.MemberOrder/getParams", params, "get"),
  getOrderList: (params) => request("/member.MemberOrder/list", params, "post"),
  cancelOrder: (params) => request("/member.MemberOrder/cancelOrder", params, "post"),
  payOrder: (params) => request("/member.MemberOrder/payOrder", params, "post"),
  getLogistics: (params) => request("/member.MemberOrder/logistics", params, "post"),
  getOrderCode: (params) => request("/member.MemberOrder/getOrderCode", params, "post"),
  submitEvaluation: (params) => request("/member.MemberOrder/submitEvaluation", params, "post"),
  confirmReceipt: (params) => request("/member.MemberOrder/confirmReceipt", params, "post"),
  getOrderInfo: (params) => request("/member.MemberOrder/info", params, "post"),
  submitService: (params) => request("/member.MemberOrder/submitService", params, "post"),
  returnGoods: (params) => request("/member.MemberOrder/returnGoods", params, "post"),
  getOrderTransaction: (params) => request("/member.MemberOrder/getOrderTransaction", params, "get"),
};
